language: ruby
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
cache: bundler
before_install:
- gem install bundler -v 2.1.4
install:
- bundle config path vendor/bundle
- bundle install
- nvm install --lts
- npm i -g yarn
- yarn
script:
- bundle exec rubocop
- bundle exec rails db:setup
- bundle exec rails webpacker:compile
- bundle exec rspec
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- echo -e "Host $DEPLOY_DOMAIN\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rvm use $(< .ruby-version) do bundle exec cap production deploy
  on:
    branch: master
