language: ruby
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
cache:
  bundler: true
  yarn: true
install:
- bundle install
- nvm install node
- npm i -g yarn
- yarn
script:
- bundle exec rails db:setup
- bundle exec rails webpacker:compile
- bundle exec rails test
- bundle exec rails server -e test -d
- yarn run cypress run --record --key $CYPRESS_KEY
before_deploy:
- openssl aes-256-cbc -K $encrypted_545545218908_key -iv $encrypted_545545218908_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- echo -e "Host $DEPLOY_DOMAIN\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rvm use $(< .ruby-version) do bundle exec mina deploy
  on:
    branch: master
env:
  global:
  - secure: dVpb9AUjWXd5CNueRcYksU4leifvzi296vj2XZwM90ETaPCmS3UnsugY9B9/xJx2owm4lieOzwsMwHqMDIMMYaXhD/7Y4E6kWekSZ+kFwnf5328qM9EmRavEsqt92PVAOZv8rxX1buYnTa1V2ZMhlPwxIlBkM4y+ywFA+SXBECErVPfMVqmtrXS5K9ACxdpYb/lbAORa6e+peE/fyMFxKIwapDZ1tsmtWQXrjAwlIhkidz88kfO4JwfKu013W0cMS09SPHSXBgJNDB+zQI5tUyANExMPHfQfMc5MAt5M7dPCMMp/a2vXSEtG562gzKnhLq/krZD9AfuDimBQzn1JRWz8WDQOQ+OLqaYBMiqGnMS3t97yqEBXLtZGQ53EklOE9X/VyddFw0t3SDLzBULy8ln7N37VCpexvPJuB/61fbg5Yj1AvTmKw1PWKkjOx9DT0la9kR2vPCWqvgiNuuA7ieKC/yuntCw+CSFFblwdUt6i0v2HmaquTeND5EW9C33pmyfseAGK2MQmjjVarQ/FEMc4Xsi8pZkgxbt1lnPb0y4n8dMAQMdgOiZSaS7KcT/5r3AHRlzaHqDsvoV8F6vP4iyOwTp7Ck70+QdK47z9SMo8lqx7fYsdrc0nmpT75nJL3x7JCl9QpyLa546A1DI3ee82h4hs6Z1oJREpuROR2tk=
  - secure: qFMZ3g1d8U4FKXhIOAYN17ntK139veaEFhz6BDXfXO9tm5gfq7WbhA7kRmn2tojGmnqdUJJuZL3tSj/Rr/Z8/VsrmsQgTH2DvF01eStciEy1xUKFVZGtq0lIKEoHzY23myFspB9FqluOjZi7FJ76pSGWMxGTnX6OiRR0FyMRrlUFNwjuA11aqyoTq2ThtwPljVFnzH/+5MWwq0uRDAp9Ie00Y1z9VRy5585S+LsBEPPcUhcBw/Y6PGQPfJsbpXO9G1F/8hKHiifP8Q7MV4LCJyjjQgxGOTheMQyBMhL+yYsVFesOZGGqH4zhfvGJ1Gazpbl6b2eNvqPwBoCLsEB4iFKlV/eplKoKhld5CJZCeRtDRvlbFpRL7E7CgB6gqC8KTqhJ4YIqQrDl6QH7/pU3bQlCFpoz9P5ACFQ6tbKlef7gVqWU2Ci0J7vXE0m3YYBHON4InQSmfhc0nX7G9JoNxGADPSntGBV3ViVRRT4Ictf70VDiIb6HufmcFsiyPcKBxWHP5fXZcUmEUvvfU6cb+sHX51PhiXEgODkQOsAev2M7koZuWDx5EBPrwBcr6rs5MxFHRtS9qyp/6U019URCpBLSOL6miNHV6MQF36sKNGbaHdOKx8Im7dRX/PPNxwz3x/axqDRlxCVTxyGxW6P17/+uy1qbEy+Mxy/IGBDCmyQ=
  - secure: jgLHrJgGBBzq83Qlhju7Gd01wClDT/xMCHO2jl36RR0MGwQNWUl+lQN9OXSBH4zLgW6T1LLK7nxfVMhbroe7DUQiAN3OCBSASxSzKBU3DK8GfLpUJkqRp3oJxI6ozU6rYi2XLc/b4hM8opBocAo1Dn+jvbGl7MtNrb6tskMBUIAYeDj61GyOLM0z5w5MZTVmrVZCOQgdTZPdWbvjhS4IFgCN/wzp7Rrb4ZV5Kbr1nzr3pAgQkYnDajkaO+CzsH6W4rwtJZY5/ivnu16csJkqULhXp09oSo1o14wFbKuP3ZdwfjCli1xU+cMA+78EtODObnEce/dkQEpR+MCId7gYHuseuwKeLKcYxlRgtUUrvMv7jUoztiPijTAxn5UHSJ45mSvbdQiY93jIkL8SoTC4G48ug1UagDTzvW0Q4cMquuQKI3aC8nh3imGiGlh08DHJD+ChzhxGeJ13TgGCornVvN3Qae7oPpvqU27i+HoFkbNxPa8GM2QM0gDlci6lJ0spY9ZMFYXkE54b93tlNMgTJPWgtSl8jmp8c7Ks5cxYiGAiSvjfFsjGwhNlMq2j4seswQ9t5iD/OzE9vN3xloPxHFSuZV8M6CjxtPqSOn4wDYibFGSsr75PwWeeD6P+7B+j1sR/FMJYgHdBGIbaArtVf1t84xBzbOMKIk1NZL4fIrI=
  - secure: eX7tH3B2kLqdhznA0u1Ndv7CiV6UzMsO9Tm2aixm0/5G2IRjTq/V1q90aj0Als5kU1+B92KkdKxvqnph6O2pqgnm2znQnPv5RVxVKukcvXzJzk9k+DEGHzR/TAIVgrpMcUVMnankycEpndCsswgVVPfpjdLvaqTLm9ihCqBMdDXpvmTGA2HvqE6fuXCio6Qz1KitjFPo7ggBGppsT0rxmd3UBW+c+F5DC68YKmkadHnT41hwJr9bfQeIZd1FuJD3KWvXy8HWbLsCU43Dsx2iJ+lIkpVRqQfZto9DnwDqrPByT6a9JvPgXRLMBcakvUUm9px4CG21zY/vliO5Dm5vDX6TXMLTbtZOZ/a/A5Ib5vHA+CbEseHG3nbL/bMN8nlxoNs1Ts1pCyfLf/0gAW2C0CGIdy0bQLVQ6ZTUWNDodAQN0kJqfM0RnmgV4v1mR3XInspT9G59MY0j7LMhVtYt9dnIpz+53RMbX6q0SO1Y3u/4/Gx7Qldkop+a8Ryrpy416nD6lgiJurdgMmhI2JxcXkZ2pO5J9yX0rSKRH7BFJfTvSmOEA5anH2Jp5Fl/HzGZ5BzQokAuJGla9ouKbF271jP1P9apD+ZYOE23WsYx7gi4i2PmOoPtEF1kQct5cao6OCpd6QBC2U6KL080LVYW14iRGbJ4hGiY/hRRIXbFjE4=
