language: ruby
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
install:
  - bundle install
  - nvm install node
  - npm i -g yarn
  - yarn
script:
  - bundle exec rails db:setup
  - bundle exec rails webpacker:compile
  - bundle exec rails test
